### ISSUE TITLE
全面失败

### ISSUE THREAD

**Issue by shinji211** [YaoZeyuan/stablog#104]
最后一次正常使用大约是4月左右，刚本来想备份4-6月的微博，但总是出错，不管怎么设置日期，都只会备份4月1-9日或者4月9-9日，或者完全错误的日期，无法和以前一样使用。尝试几次之后觉得可能重装一下会好，就下了安装包重装，结果好了，之前的备份全部被自动删除无法恢复。不知会不会修正，总之报告一下。

**Comment by YaoZeyuan** [comment]
已修复, 在https://www.yaozeyuan.online/stablog/ 下载最新版即可
