### ISSUE TITLE
谢谢姚总

### ISSUE THREAD

**Issue by gemkeeper** [YaoZeyuan/stablog#111]
谢谢姚总

**Comment by OfcourseIstillLoveU** [comment]
可以分享一下吗，我也找不到3.3.0的exe，下了yarn还没研究明白怎么运行- -

**Comment by gemkeeper** [comment]
遇到2个网友来问，解释下，是这样，exe不适宜发布出来，因为围脖服务器维护员会发现有这个东西存在，这是任何一个服务器都忌讳的，他一定会修改端口让exe失效，这次的失效很可能就是因为针对这个而故意修改的。现在是姚老师还在维护生菜，万一以后姚老师因故没有精力再更新了呢？那这个岂不就彻底报废了？其实姚老师已经把生菜洗好切好了，把熟菜发出来反而影响不好。各位自己烹调吧，这样反而活得久一些。

**Comment by OfcourseIstillLoveU** [comment]
明白了，我再多多研究下，感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gemkeeper ***@***.***&gt;
发送时间: 2022年7月31日 01:10
收件人: YaoZeyuan/stablog ***@***.***&gt;
抄送: OfcourseIstillLoveU ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [YaoZeyuan/stablog] 谢谢姚总 (Issue #111)





 
遇到2个网友来问，解释下，是这样，exe不适宜发布出来，因为围脖服务器维护员会发现有这个东西存在，这是任何一个服务器都忌讳的，他一定会修改端口让exe失效，这次的失效很可能就是因为针对这个而故意修改的。现在是姚老师还在维护生菜，万一以后姚老师因故没有精力再更新了呢？那这个岂不就彻底报废了？其实姚老师已经把生菜洗好切好了，把熟菜发出来反而影响不好。各位自己烹调吧，这样反而活得久一些。

**Comment by YaoZeyuan** [comment]
> 遇到2个网友来问，解释下，是这样，exe不适宜发布出来，因为围脖服务器维护员会发现有这个东西存在，这是任何一个服务器都忌讳的，他一定会修改端口让exe失效，这次的失效很可能就是因为针对这个而故意修改的。现在是姚老师还在维护生菜，万一以后姚老师因故没有精力再更新了呢？那这个岂不就彻底报废了？其实姚老师已经把生菜洗好切好了，把熟菜发出来反而影响不好。各位自己烹调吧，这样反而活得久一些。姚老师这次不把熟菜发出来，我现在已经明白他的用意和苦心了。

其实是Github Action构建失败...导致我一直没办法发布mac平台下的安装包, 今天刚搞定, 发布到https://www.yaozeyuan.online/stablog/  上了已经👻
