### ISSUE TITLE
现在下载的软件版本无法正常导出与备份

### ISSUE THREAD

**Issue by yumitter** [YaoZeyuan/stablog#113]
您好，
现在的版本导出不了
![image](https://user-images.githubusercontent.com/39401762/182027722-b54ea674-feb3-4517-a750-9cae82ab5ebd.png)

可以求一下最新版本3.3.0的exe吗？邮箱1574598403@qq.com，感恩的心❥

**Comment by YaoZeyuan** [comment]
已发布在官网 https://www.yaozeyuan.online/stablog/

**Comment by yumitter** [comment]
> 已发布在官网 https://www.yaozeyuan.online/stablog/

谢谢！
