### ISSUE TITLE
建议：可选是否生成电子书、可选保存到目录

### ISSUE THREAD

**Issue by zangbob** [YaoZeyuan/stablog#16]
非常好用，感谢之极，已star 

0. 能否让用户自行选择是否生成电子书，以及电子书的格式除了PDF外，能否支持mobi、epub之类呢？
1. 可选由用户自选选择保存生成的电子书的位置，而不是放在软件目录下。

**Comment by YaoZeyuan** [comment]
mobi是私有格式, 这个不能做. 

epub的问题是多看阅读对css样式的兼容性非常差, 而且难以调试. 稳部落的前身, 知乎助手会输出epub文件, 但是因为css太难写, 所以写稳部落的时候把这个功能砍掉了

允许设置电子书输出位置这个可以考虑, 我加到需求列表里
