### ISSUE TITLE
提示所有任务完成，但是电子书文件夹为空

### ISSUE THREAD

**Issue by jxyddtc** [YaoZeyuan/stablog#19]
应该是generate这一步出现问题，现在我的电脑有20多GB的缓存材料，不知道能否直接进行生成步骤......不想再重新爬一天了......

**Comment by YaoZeyuan** [comment]
把备份页码范围改成0~1就行了...

& 

需要提示一下, 现在有个已知bug, pdf体积超过2gb会导致pdf文件打不开, 导出的时候最好限制下时间范围~

**Comment by jxyddtc** [comment]
> 把备份页码范围改成0~1就行了...
> 
> &
> 
> 需要提示一下, 现在有个已知bug, pdf体积超过2gb会导致pdf文件打不开, 导出的时候最好限制下时间范围~

您好，按照您说的做了，时间范围设置的是一年，在进行到一半的时候提示如下错误：
正在处理第8/12卷中,第151/230条微博 
2020-03-13 00:20:43.973: [GenerateCustomer] catch error 
2020-03-13 00:20:43.973: [GenerateCustomer] Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot

PS：此时盘内的内存是够的

**Comment by YaoZeyuan** [comment]
Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot
----------
pdf渲染异常, 重新启动一次就好了
