### ISSUE TITLE
系统设置问题

### ISSUE THREAD

**Issue by kokiku1** [YaoZeyuan/stablog#22]
备份页数选择0-1，但是输出只能输出最新的，更改时间无变化。
请问第一次备份需要全部备份，然后如果设置一年跨度输出，下一次备份页数就可以选择0-1对吗。
不知道有没有表达清楚。。。。

**Comment by kokiku1** [comment]
补充一个问题，备份页数的时候可以暂停，下次再继续吗

**Comment by YaoZeyuan** [comment]
是的, 备份微博和输出内容是两个独立任务(独立配置项, 互相没有关联)
