### ISSUE TITLE
实际执行的Chromium版本问题，仍旧是32位的

### ISSUE THREAD

**Issue by logmeoutin** [YaoZeyuan/stablog#23]
win7-x64，主程序执行后发现win64-686378下的Chrom并没有运行，仍旧是32位的chrome。

**Comment by YaoZeyuan** [comment]
chrome只负责把网页转换成jpg图片, 这个问题应该不影响实际使用

(增加64位模式是因为32位的Electron运行环境下pdfkit不能生成大于2GB的pdf文件, 使用体验很糟糕, 所以加个64位版本hack一下

**Comment by logmeoutin** [comment]
谢谢回复
是的，不影响使用。只是打包的安装文件大了一些。
-------closed
