### ISSUE TITLE
希望能添加一个新功能，选择输出的文件夹

### ISSUE THREAD

**Issue by zyzll1234** [YaoZeyuan/stablog#24]
希望能添加一个新功能，选择输出的文件夹
c盘撑爆了。。
还有就是希望能添加一个重新输出pdf的功能，输出了好几次体积都在4个G以上..打不开..

谢谢

**Comment by logmeoutin** [comment]
1. 程序可以安装在别的盘符下面的。

2. Yao老师在https://github.com/YaoZeyuan/stablog/issues/19#issuecomment-597995862 已经回复了这个问题的解决方案。建议你把所有issues爬一遍～～

**Comment by zyzll1234** [comment]
谢谢~


| |
郑煜哲 Yuzhe Gerald Zheng
|
|
zyzll1234@163.com
|
签名由网易邮箱大师定制
在2020年3月23日 08:48，logmeoutin<notifications@github.com> 写道：

程序可以安装在别的盘符下面的。

Yao老师在#19 (comment) 已经回复了这个问题的解决方案。建议你把所有issues爬一遍～～
