### ISSUE TITLE
微博名长的话可能一行显示不全，不好看

### ISSUE THREAD

**Issue by northword** [YaoZeyuan/stablog#25]
需要改一下CSS，要不然名字长，会自动换行，就不太美观。
 
 这是原来的样式
![这是原来的样式](https://storage.live.com/items/28C1032A24A9C53B!10359?authkey=AHAx3GOYEKGqm8I)
 
建议的修改
![建议的修改](https://storage.live.com/items/28C1032A24A9C53B!10358?authkey=AHAx3GOYEKGqm8I)
 
 或者把高度加大
![或者把高度加大](https://storage.live.com/items/28C1032A24A9C53B!10357?authkey=AHAx3GOYEKGqm8I)

**Comment by YaoZeyuan** [comment]
done, 已改
