### ISSUE TITLE
个人主页URL无法自行输入，只能点击自动同步，请问是不是不能备份别人的微博啊

### ISSUE THREAD

**Issue by Lafindumonde** [YaoZeyuan/stablog#27]

**Comment by uahoo** [comment]
不能备份别人的微博？

**Comment by Zoro-Harvard** [comment]
可以备份别人的微博。不过需要自己用python继续操作。https://mp.weixin.qq.com/s?__biz=MzIyMjg2ODExMA==&mid=2247485035&idx=1&sn=2cda78ee89f39317decaca51c128e150&scene=21#wechat_redirect

整不来的可以不用这个“稳部落”软件，换成“Octoman”这个Chrome插件。（可以直接备份别人的微博）

**Comment by uahoo** [comment]
好

**Comment by YaoZeyuan** [comment]
> 不能备份别人的微博？

这个之前因为贴了赞赏二维码, 要规避版权问题, 所以干掉了导出任意用户微博功能.

3.0.0版本已恢复该功能.
