### ISSUE TITLE
如何清除微博登入页面的缓存？

### ISSUE THREAD

**Issue by xieft** [YaoZeyuan/stablog#29]
我有一个炸的不能在炸的微博号，登入后显示一片空白（如图），所以也没有办法退出登入，在清空了所有浏览器的缓存，并卸载重装**稳部落**后，该问题还是没办法解决。麻烦告知解决方案。
![image](https://user-images.githubusercontent.com/35829258/84005882-6ace7c00-a9a0-11ea-87a9-6aae2eb82731.png)

**Comment by YaoZeyuan** [comment]
稳部落的原理是模拟浏览m.weibo.com, 炸到没法登录m站就真没救了, 节哀...

**Comment by xieft** [comment]
我是要登其它正常帐号呀，但是因为这个帐号的原因，我不能登入
2021年4月8日 +0800 22:30 姚泽源 ***@***.***>，写道：

**Comment by YaoZeyuan** [comment]
> 我是要登其它正常帐号呀，但是因为这个帐号的原因，我不能登入 2021年4月8日 +0800 22:30 姚泽源 ***@***.***>，写道：
> […](#)
> 稳部落的原理是模拟浏览m.weibo.com, 炸到没法登录m站就真没救了, 节哀... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

理解. 这个确实不好找

你在这里找找试试 

C:\Users\[用户名]\AppData\Roaming\stablog

或者下个[everything](https://www.voidtools.com/zh-cn/downloads/), 搜索stablog, 然后把找到的目录都删掉, 看看能清除登录记录不
