### ISSUE TITLE
用户名自动折行，customer.css需修改

### ISSUE THREAD

**Issue by logmeoutin** [YaoZeyuan/stablog#33]
max-width: 500px; 
改为 width: 500px;

**Comment by iblueer** [comment]
发布时间和用户名一样都自动折行了，需要修复。
![image](https://user-images.githubusercontent.com/3581944/85924967-45aa9a80-b8c8-11ea-85c8-1c505c3d4589.png)

**Comment by YaoZeyuan** [comment]
感谢反馈, 已修复
