### ISSUE TITLE
已赞助，望后期加入筛选，能把转发的内容过滤掉，只显示自己发的

### ISSUE THREAD

**Issue by Uchiha-Peng** [YaoZeyuan/stablog#36]
给作者点赞，想注销微博很久了，但又舍不得自己从前过往，一直没有找到合适的备份工具，自己也写过把微博数据导出成Markdown，但是因为是测试接口，每天调用接口次数有限，导出的微博内容有些不是全文，图片也不是大图，后来就放弃了 。你写的工具非常好用，但是也发现了一些问题，比如导出的数目和实际微博数量不一致，这点让人有点抓狂。生成的pdf的话，效果也不是特别好，而且视频没法加载，建议尝试生成Markdown，图片直接通过URL加载，视频也不会漏掉。

**Comment by Uchiha-Peng** [comment]
![Screenshot_20200707_230817_com eg android AlipayGphone](https://user-images.githubusercontent.com/20633089/86803220-5cab7280-c0a8-11ea-922c-74a0093f3b09.jpg)

**Comment by Uchiha-Peng** [comment]
哈哈，我自己也用c#写了个，免登录导出公开的微博内容，生成Markdown，欢迎使用。[here](https://github.com/Uchiha-Peng/weibo2markdown)

**Comment by YaoZeyuan** [comment]
感谢支持  

3.0加入了只导出原创微博功能, 可以试试哈哈
