### ISSUE TITLE
建議加入備份評論功能

### ISSUE THREAD

**Issue by aa717648tw** [YaoZeyuan/stablog#37]
因為很多跟朋友的討論都在評論裡
不知道備份評論內容這樣的功能可不可以研發看看呢?

實在非常謝謝您開發了這個程式
非常非常感謝!

**Comment by YaoZeyuan** [comment]
将来可以考虑加一个抓取前10条评论的功能, 我列到todo里吧, 感谢反馈

**Comment by aa717648tw** [comment]
穩部落的開發者您好:
一直以來都有使用這個軟體備份的習慣
近期看見有更新，就下載了新的3.1.0版本
結果備份之後發現有遺漏的狀況
例如2019.10.31我明明有好幾篇文章
但備份成PDF出來後剩下一篇
我會去網頁上找，那些文章都還是存在的
卻沒有備份到

謝謝您無私的開發
在此給予使用回饋
不知道您看不看得到


姚泽源 ***@***.***> 於 2021年5月23日 週日 下午2:14寫道：

**Comment by YaoZeyuan** [comment]
hello, 方便提供一下备份的目标url吗, 我测试一下
