### ISSUE TITLE
没有导出电子书

### ISSUE THREAD

**Issue by chandy89830** [YaoZeyuan/stablog#38]
只在缓存文件夹中看到零散的图片，还有显示不全的HTML文件，电子书文件夹为空，没有生产任何PDF文件

**Comment by YaoZeyuan** [comment]
之前是通过内置Chrome浏览器生成图片, 然后再打包成pdf. 这里如果内置的chrome启动失败, 就会导致渲染失败&无法输出pdf的问题.


3.0.0版之后改为利用Electron平台本身渲染pdf, 可以换3.0.0试下
