### ISSUE TITLE
为什么我输入了日期还是从头开始备份啊？

### ISSUE THREAD

**Issue by wzhb** [YaoZeyuan/stablog#42]
我明明限制了时间，好神奇
![Snipaste_2021-03-29_16-20-56](https://user-images.githubusercontent.com/14255631/112807928-06091d00-90ab-11eb-84dd-64450f9824cd.png)
![Snipaste_2021-03-29_16-20-37](https://user-images.githubusercontent.com/14255631/112807939-09040d80-90ab-11eb-81be-45a0138b523a.png)

**Comment by YaoZeyuan** [comment]
3.0.0有bug, 每次开始备份时会重置备份范围, 导致从头开始备份, 3.1.0已修复
