### ISSUE TITLE
是不是备份是倒序备份？能不能从第一条微博开始正序备份？

### ISSUE THREAD

**Issue by wzhb** [YaoZeyuan/stablog#43]
第一次备份3000多页太长时间了

**Comment by wzhb** [comment]
备份页码范围代表什么含义？比如我开始用的时候微博最多3001页，我停止了。使用一段时间后编程3100页，我该怎么弄？

**Comment by YaoZeyuan** [comment]
使用的是倒序备份. 从最后一条微博向前备份.

微博那边限制访问频率不能高于20秒/次, 所以备份时间会巨长, 从自家电脑上慢慢跑吧, 反正备份一次就ok了

页码 = 总微博数/10

**Comment by wzhb** [comment]
> 使用的是倒序备份. 从最后一条微博向前备份.
> 
> 微博那边限制访问频率不能高于20秒/次, 所以备份时间会巨长, 从自家电脑上慢慢跑吧, 反正备份一次就ok了
> 
> 页码 = 总微博数/10

是这样，不知道为什么，2020年4月以前的微博无法备份。而且一共3600多页，无论我怎么选择页码，都是全部备份

**Comment by YaoZeyuan** [comment]
如果是只能备份到4月的话, 可能是博主设置了只显示最近一年的微博?

**Comment by wzhb** [comment]
我的微博全部可见，而且8月份的也少一半。每次设置页码也没用，都是重新开始备份
![Snipaste_2021-04-08_22-55-41](https://user-images.githubusercontent.com/14255631/114049478-0e890100-98be-11eb-8632-31d0a67107c0.png)

**Comment by YaoZeyuan** [comment]
> 我的微博全部可见，而且8月份的也少一半。每次设置页码也没用，都是重新开始备份
> ![Snipaste_2021-04-08_22-55-41](https://user-images.githubusercontent.com/14255631/114049478-0e890100-98be-11eb-8632-31d0a67107c0.png)

知乎上私我下微博地址, 我跑跑试试

https://www.zhihu.com/people/404-Page-Not-found

**Comment by YaoZeyuan** [comment]
问题在3.1.0中已修复
