### ISSUE TITLE
MacOS下打开后一片空白，退出后显示A JavaScript error occurred in main process但是只有一个磁盘且已设置为可写入，请问如何解决。。

### ISSUE THREAD

**Issue by plasticgu** [YaoZeyuan/stablog#48]

**Comment by plasticgu** [comment]
![image](https://user-images.githubusercontent.com/82740816/115133375-47517480-a03a-11eb-9219-72d7f2cb52a7.png)

**Comment by TsuiEnPeng** [comment]
同遇到这个问题

**Comment by jessck-jzy** [comment]
same question~ how to solve this problem

**Comment by ssabriel** [comment]
mac os遇到同样的问题。退出之后没有报错，但一直就是白屏状态。

**Comment by YaoZeyuan** [comment]
该问题已复现成功, 我研究下

**Comment by YaoZeyuan** [comment]
已添加到3.2.0需求收集中

**Comment by YaoZeyuan** [comment]
已确认, 3.1.0的mac版可以使用.
