### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by YaoZeyuan** [YaoZeyuan/stablog#5]
- [ ] 考虑导出为docx/CHM的功能, 方便用户二次编辑
- [x] 添加按钮，支持直接打开电子书存放目录
- [x] 生成新电子书时，不要删除旧的电子书目录
- [ ] 有图/无图 选项说明不清晰，需要说明如何保存原图
- [ ] 微博登录界面不支持扫码登录（嵌下web版登录页面试试？）
- [x] 预览数据时, 点击链接不要跳转(回不去)
- [x] 完善预览样式, 也做到和微博h5一致
- [x] 支持自定义配置pdf清晰度
- [ ] 允许设置电子书输出位置, 输出到指定文件夹/而不是软件所在文件夹
- [x] 对于被封id(例如sunnyman11, 对应uid地址为https://m.weibo.cn/u/1027332955), 直接调用接口转换为uid会提示该用户已被封, 需要用户自行访问m站地址才能拿到uid进行抓取, 因此需要写份文档, 告知用户该如何获取自己的uid.(或者联系一位账号被封用户, 配合查一下转换方案)

软件要足够易用，最好随意一个人都能操作

**Comment by YaoZeyuan** [comment]
- [ ] pdf封皮可以改善， 可以参考[微印](https://www.weiyin.cc/)项目的封皮 

参考 => ![image](https://user-images.githubusercontent.com/7150325/70865534-bbd55880-1f99-11ea-99c9-245541cf0427.png)

![image](https://user-images.githubusercontent.com/7150325/70865554-e1626200-1f99-11ea-9ccf-2da111236413.png)

https://weibo.com/2257541662/Cc2BllTns?type=comment#_rnd1576426827847

**Comment by cmsax** [comment]
如果能够增加其他元数据的获取就好了：

- 阅读数量
- 评论详情
- 转发详情

**Comment by YaoZeyuan** [comment]
阅读数拿不到的

现在20s调一次接口, 评论列表/转发列表需要再调接口获取, 抓这些数据的话会导致备份时间过长.

毕竟不是专业爬虫, 先这样吧~

**Comment by YaoZeyuan** [comment]
> 如果能够增加其他元数据的获取就好了：
> 
> * 阅读数量
> * 评论详情
> * 转发详情

阅读数拿不到的

现在20s调一次接口, 评论列表/转发列表需要再调接口获取, 抓这些数据的话会导致备份时间过长.

毕竟不是专业爬虫, 先这样吧~

**Comment by YaoZeyuan** [comment]
常用todo都完成了, 先close了
