### ISSUE TITLE
6条建议：windows版

### ISSUE THREAD

**Issue by kingkongace** [YaoZeyuan/stablog#50]
**6条建议：windows版**

我的微博，有几万条内容，在微博数量巨大时，备份是一件非常难的事，加之每页需要停顿20秒，那么，备份时间就太长了，可能要连续工作许多天才有可能。但是，正常情况下，电脑不可能连续工作几百小时。

现在的问题是，每次电脑打开就又从第1页开始备份，这个方式不合理。

整体建议如下：

1.设置单独备份，比如自主选择“第N条”到“第M条”的任意选项。这样就能随时备份，可能分时段，或分批次，随时备份。当有几万条微博时，这个功能非常重要，也是必须的功能。

2.设置时间倒序与时间顺序，是从2010年到2020年，或2020年到2010年等皆可自由选择。

3.也可以直接设定“按年月进行备份”，因为“年月”比较合理，一年只有12个月，备份相对方便。或者可以自由选择“从某N时间,备份到某M时间”，这样更加合理。

4.从目前版本3.0来看，“备份范围”中的“从N面备份到第M页”并没有实际作用，至少我目前使用情况看，没有作用。也许是我使用方式错误了吧。或者是并不能真正程序执行？

5.希望在备份的某个时刻，突然想“停止时”，也能直接导出电子书。实际上，到目前为止，我花了几个小时备份，都没有导出一本书，也没有导出一页，这是否是BUG？

6.希望可以选择“备份停止”功能。

**Comment by YaoZeyuan** [comment]
感谢反馈, 3.1.0版本已经加上了这些功能, 欢迎试用
