### ISSUE TITLE
备份微博时无法登录

### ISSUE THREAD

**Issue by Yoyodust** [YaoZeyuan/stablog#57]
你好，我之前登录了一个已经被封的微博账号，能够登录上去，但是页面完全异常了，也找不到选项退出登录。我试过卸载重新安装，但是软件还是默认登录了异常账号，请问我应该怎么退出登录呢？谢谢

**Comment by YaoZeyuan** [comment]
目前几乎无解, windows用户可以试下这个方法

1. 安装[everything](https://www.voidtools.com/zh-cn/)
2. 搜索`stablog`, 删除带stablog关键字的所有路径/文件(人工清除缓存)
3. 重新安装稳部落, 再打开就可以重新登录了
