### ISSUE TITLE
能够提升PDF输出的清晰度

### ISSUE THREAD

**Issue by 1812523544** [YaoZeyuan/stablog#7]
您好，我用您的工具生成的PDF清晰度不够好，能否加一个选项，生成清晰的PDF呢，哪怕多占用存储资源，另外，谢谢您的工具，给了我很多帮助。

**Comment by Rex-Diego** [comment]
最好可以输出为文字可复制，图片是原图的PDF～十分感谢！

**Comment by YaoZeyuan** [comment]
ok, 记下了
