### ISSUE TITLE
备份中途经常中断

### ISSUE THREAD

**Issue by tinyhitoil** [YaoZeyuan/stablog#8]
您好，我前几天第一次使用软件，备份了近两年多的微博，使用正常，pdf文档也很清晰，感谢您的开发。然而那次之后就再也无法顺利备份了，都是在中途突然断开，显示账号被认为有风险6小时后再试，但再试依旧失败，想请教一下这个问题如何解决？

**Comment by YaoZeyuan** [comment]
旧版本没载入cookie, 所以实际上是无登陆状态在抓取...

更新到1.7.0版本就行
