### ISSUE TITLE
【bug】导出数据完成，卸载软件后数据丢失

### ISSUE THREAD

**Issue by cfjin** [YaoZeyuan/stablog#84]
* 我安装完成后,把微博数据备份了下来；
* 然后我查看了下，没有问题；
* 然后我把软件卸载了（无意冒犯的意思）；
* 最后我备份的微博都没了；

## 希望在卸载的时候给个提示，是否保存用户数据，或者可以让用户选择备份地址，避免数据丢失

**Comment by YaoZeyuan** [comment]
因为数据在软件目录里, 卸载的时候会把软件目录整个删除...

备份完成后记得把生成的pdf拷出来一份, 你不是第一个被坑到的人...
