### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by MingshiGao** [YaoZeyuan/stablog#9]
想知道有没有办法备份那种已经炸了，只能自己登陆看的号

正常号的备份非常顺利，已打赏已安利，谢谢作者

**Comment by askerlee** [comment]
同求。我的微博挂了所以想用这个备份

**Comment by kokiku1** [comment]
同。但是好像输入主页地址没反应

**Comment by YaoZeyuan** [comment]
@MingshiGao @askerlee @kokiku1 

1.7.0版已支持该功能, 欢迎更新使用

**Comment by MingshiGao** [comment]
<img width="446" alt="Screen Shot 2020-03-03 at 3 35 25 PM" src="https://user-images.githubusercontent.com/39345035/75817263-b69bd480-5d64-11ea-9f15-c7699468423a.png">
试了一下，似乎不行
炸号之后，我发现登陆的话url从 https://m.weibo.cn/u/1687243315 变成了https://m.weibo.cn/1687243315，不知道这个有没有影响

**Comment by MingshiGao** [comment]
谢谢哥，想给您跪下
