### ISSUE TITLE
已经炸号的是不是无法同步

### ISSUE THREAD

**Issue by wzhb** [YaoZeyuan/stablog#92]

**Comment by lljxx1** [comment]
https://greasyfork.org/zh-CN/scripts/445022-%E5%BE%AE%E5%8D%9A%E5%A4%87%E4%BB%BD
试试这个

**Comment by YaoZeyuan** [comment]
看登录m.weibo.cn后能不能看到自己的微博内容, 能看到就能备份, 反之则不能
